### ISSUE TITLE
[BUG] Incorrect display of adaptive folder icon size

### ISSUE THREAD

**Issue by Majo111** [G-dH/vertical-workspaces#92] opened 2023-06-16 09:07 UTC
I realized incorrect displaying of adaptive folder icon size.  I add a picture:

![Snímka obrazovky zo dňa 2023-06-16 10-44-56](https://github.com/G-dH/vertical-workspaces/assets/31368840/4dccbb34-1a85-4665-b6f8-228685c59c76)

**System:**
 - OS: Manjaro
 - Version of V-Shell extension: 30
 - Source of installation: [e.g. extension.gnome.org, GitHub]

**Comment by G-dH** [comment] 2023-06-18 19:17
This can happen under certain conditions when the algorithm gets incorrect allocation data. I'll try to add some self-fixing solution. For now, you can use a fixed icon size.

**Comment by Majo111** [comment] 2023-06-19 14:23
Thanks. I appreciate it.

**Comment by Majo111** [comment] 2023-06-20 08:38
I tried different sizes, but its still a problem.

**Comment by G-dH** [comment] 2023-06-20 09:06
What exactly is the problem?

**Comment by G-dH** [comment] 2023-06-20 09:45
Do you use screen scaling?

**Comment by Majo111** [comment] 2023-06-20 10:53
No. Sizes of icons in folders are too big or too small. In some cases icons are cropped.

**Comment by Majo111** [comment] 2023-06-20 10:58
If I change size from adaptive to for example 96 and back, than all is working.

**Comment by G-dH** [comment] 2023-06-20 11:01
Have you tried just closing and reopening the folder?

**Comment by Majo111** [comment] 2023-06-20 11:29
Yes. I have tried this.

**Comment by G-dH** [comment] 2023-06-20 11:56
There was a bug affecting the adaptive folder grid dimensions (rows/columns), please try to [update the extension from the GitHub repository](https://github.com/G-dH/vertical-workspaces#installation-from-github-repository) and let me know how it works now.

**Comment by Majo111** [comment] 2023-06-20 12:14
How can I backup current settings?

**Comment by G-dH** [comment] 2023-06-20 12:37
Updating the extension will not affect your current settings.
You can also save your configuration to any of the four profiles before testing different options.

**Comment by Majo111** [comment] 2023-06-20 13:25
Thanks. Its working for now.

**Comment by G-dH** [comment] 2023-06-23 16:15
Can you please try the latest update to see if it fixes the fully adaptive folders?

**Comment by Majo111** [comment] 2023-06-23 19:26
When I open some folders at first, its looks like this:
![Snímka obrazovky zo dňa 2023-06-23 21-16-26](https://github.com/G-dH/vertical-workspaces/assets/31368840/7cc2d3d0-e7f3-4f2a-8af5-fa89128fb701)

And this:
![Snímka obrazovky zo dňa 2023-06-23 21-16-46](https://github.com/G-dH/vertical-workspaces/assets/31368840/58b74c60-eb9e-43f7-b93f-9b0dd70a3ebb)

Than its open folders correctly. But I am not sure, if this folder shows like it has, because of size:
![Snímka obrazovky zo dňa 2023-06-23 21-18-26](https://github.com/G-dH/vertical-workspaces/assets/31368840/f0e2a00b-53ec-4f09-9ed6-32a248d1ba59)

**Comment by G-dH** [comment] 2023-07-05 08:27
I assume the problem still exists in the latest version, is that right?

**Comment by Majo111** [comment] 2023-07-05 18:41
Yes, it is.

**Comment by G-dH** [comment] 2023-08-01 15:02
Let's define the problem - from what I can see, it seems like app folder padding is a bit larger than it suppose to be and the bottom edge touches the edge of the screen. However I'm unable to reproduce this on any of my systems. Are you using default Shell theme? If not, is it reproducible with the default theme? Or is this issue about something else?

**Comment by Majo111** [comment] 2023-08-06 08:36
I use different gnome shell theme. And on this theme when I click on large folder at first, the bottom edge touches the edge of the screen. At other click is all ok (the bottom edge don't touch the edge of the screen anymore).
When I use default theme, the bottom edge always touch the edge of the screen.

**Comment by G-dH** [comment] 2023-10-15 09:11
I made some corrections to the folder dialog size, can you see a difference? (install from the repository)

**Comment by Majo111** [comment] 2023-10-15 10:33
Thanks for your effort, but there is still the problem.

**Comment by G-dH** [comment] 2023-12-07 22:18
@Majo111 Anything changed?

**Comment by Majo111** [comment] 2023-12-07 22:28
Its ok now. It has changed from 45 version.

**Comment by G-dH** [comment] 2024-04-29 17:31
@Majo111 I found the culprit while refactoring the appDisplay module, the search entry visibility option was involved. I believe it's finally fixed now.

**Comment by Majo111** [comment] 2024-05-09 17:11
@G-dH All is working properly. Thanks.

**Closed** 2024-05-09 17:12 UTC
Labels: bug, awaiting response, fixed
