### ISSUE TITLE
[BUG] Grid calculation / apps sorting issue

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#160] opened 2024-05-21 23:41 UTC
Fedora 40, GNOME 46.1, V-Shell from Github repo with all latest fixes.

With latest fixes seems that some grid calculation issues are already gone, that occurred after the App Grid part was rewritten.

I have laptop with 1920x1080 display and 100% scaling plus external monitor with 2560x1440 display and 125% scaling. My V-Shell settings are 8 columns per page, rows per page is adaptive. With laptop internal screen I have 8x4 grid and with external monitor 8x5 grid. Considering screen sizes and scaling, both are perfectly good, but...

My apps sorting setting is "Custom (Default)" but for clarity, the apps are manually arranged in alphabetical order. With external monitor are my apps on two pages, this is my second/last page of App Grid:

![Screenshot from 2024-05-22 01-57-41](https://github.com/G-dH/vertical-workspaces/assets/147217565/dbd557d6-354c-45d5-91d9-c3299d6aa20f)

After restart or relogin I got often (but not always) with external monitor following result:

![Screenshot from 2024-05-22 02-00-42](https://github.com/G-dH/vertical-workspaces/assets/147217565/62dd450f-e45f-4b11-af09-17d45a94f733)

App Grid is calculated correctly for this display (8x5) but the order of apps is messed up. If I will now reload my V-Shell profile (sometimes twice) apps order gets back to normal.

I usually have my laptop lid closed and only use an external display. But if I will disconnect external monitor, I got following result:

![Screenshot from 2024-05-22 02-06-45](https://github.com/G-dH/vertical-workspaces/assets/147217565/72471762-5f3f-4ae0-8d83-fefdb5589a23)

App Grid is calculated 8x4, which is perfectly fine, butt apps order is messed up again. The difference is that with an internal screen reloading V-Shell profile, relogin or restart doesn't help, apps order stays wrong. Maybe it's because the application order and V-Shell settings are set using an external display.

**Comment by meybonomme** [comment] 2024-05-22 22:25
Using only an external display, this is what I got today after waking the laptop from sleep mode:

![Screenshot from 2024-05-22 20-04-33](https://github.com/G-dH/vertical-workspaces/assets/147217565/47761479-a467-4448-b0da-3efd2b55beb2)

Before sleep, everything was fine, the App Grid was 8x5, as it should be.
This has happened before, but in the meantime I updated V-Shell and the problem was gone for a few days.

**Comment by meybonomme** [comment] 2024-05-24 21:27
If grid calculation is wrong (8x4 app grid instead of 8x5 on external monitor), these commands doesn't change anything. Reloading my V-Shell profile helps, but apps order now messed up.

When I run the command
`Main.overview._overview.controls._appDisplay._orderedItems.forEach(i => print(i.id))`
nothing visible happens. 

`Main.overview._overview.controls._appDisplay._redisplay()`
after that corrects apps order.

**Comment by meybonomme** [comment] 2024-05-28 11:49
Today after the reboot I got 8x3 grid with using only external display:

![Screenshot from 2024-05-28 14-45-08](https://github.com/G-dH/vertical-workspaces/assets/147217565/5ab0ffd2-7d8e-44be-9919-cbae1cdb2fe8)

**Comment by G-dH** [comment] 2024-05-28 11:56
With the custom order setting, each icon has its own page/position properties for the grid dimensions current in the time the data was stored. When you change the grid's dimensions, these data doesn't change, and icons that don't fit are redistributed according to the current configuration.

I can fix it for disabled *Allow Incomplete Pages* option.

**Comment by meybonomme** [comment] 2024-05-30 11:19
> I can fix it for disabled Allow Incomplete Pages option.

Very good, because I have this option disabled. But the main problem is why the grid is very often calculated incorrectly.

**Comment by G-dH** [comment] 2024-06-05 23:27
Please, test the latest update.

**Comment by meybonomme** [comment] 2024-06-06 16:23
Thank you, I will test the update for a few days and then give feedback.

**Comment by meybonomme** [comment] 2024-06-08 20:21
Using only an external display, I've gotten the result in the screenshot several times after starting up the desktop. The vertical alignment is wrong, the pages are incomplete, and the order of the applications is not correct.

This seems to be the only bug at the moment based on my testing.

![Screenshot from 2024-06-08 11-50-13](https://github.com/G-dH/vertical-workspaces/assets/147217565/ab9dfa40-fe36-480f-832d-1c7860643f50)

**Comment by G-dH** [comment] 2024-06-08 20:31
Thanks!

**Comment by meybonomme** [comment] 2024-06-10 11:23
Today after restarting the computer I saw such a picture. Restarting V-Shell helped, reloading the profile did not.

![Screenshot from 2024-06-10 13-16-08](https://github.com/G-dH/vertical-workspaces/assets/147217565/ff81c038-1f54-4675-a0e5-3b589fbe6633)

**Comment by G-dH** [comment] 2024-06-10 11:31
Have you installed yesterday's update?

**Comment by meybonomme** [comment] 2024-06-10 11:39
> Have you installed yesterday's update?

Yes.

**Comment by G-dH** [comment] 2024-06-10 11:53
Was the external monitor involved?

**Comment by meybonomme** [comment] 2024-06-10 12:02
Yes, I only used the external monitor when I restarted the computer. The laptop lid was closed and the built-in display was off.

**Comment by G-dH** [comment] 2024-06-10 12:04
Try to reproduce the issue and then execute the following line from lg:
`Main.overview._overview.controls._appDisplay._redisplay()`

**Comment by G-dH** [comment] 2024-06-12 22:20
I believe that the latest refactored version of `_redisplay()` can handle any situation. I'm starting to understand the details of how the app grid works. I also sort of fixed keyboard navigation inside app folders and some other upstream glitches.

**Comment by meybonomme** [comment] 2024-06-12 22:59
Excellent! I will test the updates and then give feedback.

**Comment by meybonomme** [comment] 2024-06-13 10:13
With the laptop lid closed and only using an external monitor, I got an 8x4 app grid today after waking the computer from sleep. 8x4 is the correct grid for a laptop monitor. Everything was fine before I went to sleep, the app grid was 8x5 on the external monitor.

There are also problems with dragging icons out of the folder. Sometimes when just dragging an icon out of a folder, this happens:

![Screenshot from 2024-06-13 13-02-10](https://github.com/G-dH/vertical-workspaces/assets/147217565/992e74dd-13b4-4315-a8d9-2227d88d0a36)

When I drag an icon to another page of the app grid (for example, a folder is on the first page and I want to drag it to the second page), I often get something like this (switching app grid pages will fix this problem):

![Screenshot from 2024-06-13 02-11-58](https://github.com/G-dH/vertical-workspaces/assets/147217565/6b7a4abf-1ccc-443e-a1fb-8d69c288c466)

Then another older bug, I've always forgotten to report this one. After dragging the icon out of the folder, this is what happens most of the time (reloading V-Shell profile fixes this):

![Screenshot from 2024-06-13 02-10-35](https://github.com/G-dH/vertical-workspaces/assets/147217565/56fe4a17-5f55-42b3-8bb8-7501ef0cc100)

**Comment by G-dH** [comment] 2024-06-13 11:51
In the default app grid, this happens anytime you start dragging and there is a selected item on another page. I've fixed it partially, but the folder part needs more work.
The last screenshot also shows an upstream bug. I'll try to fix it for V-Shell, but you should report it here:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6164

**Comment by G-dH** [comment] 2024-06-14 09:25
Another update for testing.

**Comment by meybonomme** [comment] 2024-06-16 19:52
The main problems with grid calculation and app sorting seem to be gone, well done! So far, I have not been able to create a situation where the grid is calculated incorrectly or the order of applications is incorrect for either monitor.

Most of the time when I switch monitors, restart the computer, or wake up from sleep, the first time I open the app grid, I see an animation as the app grid is recalculated and the app icons are moved. In one case, it was not quite successful:

![Screenshot from 2024-06-16 21-58-07](https://github.com/G-dH/vertical-workspaces/assets/147217565/684b0445-881d-40b6-b93a-93775c0226c4)

It seems that you have also successfully fixed the upstream folder bug, because it has no longer occurred when dragging the icons out of the folder. Good job!

Unfortunately, when I drag the icons out of the folder, the app grid bug is still there and I get the following results:

![Screenshot from 2024-06-15 16-23-43](https://github.com/G-dH/vertical-workspaces/assets/147217565/ec39163c-e8e7-44e6-9fed-ff53c2473bfc)

![Screenshot from 2024-06-15 01-29-30](https://github.com/G-dH/vertical-workspaces/assets/147217565/5d9f1b59-48fa-4fae-81a0-e23699a1160a)

![Screenshot from 2024-06-16 22-39-40](https://github.com/G-dH/vertical-workspaces/assets/147217565/6b8c4bee-cea5-4f28-b6f1-22d4b34e6f1e)


I have "Center Open Folders" option enabled and with external monitor all is fine:

![Screenshot from 2024-06-16 22-08-25](https://github.com/G-dH/vertical-workspaces/assets/147217565/5ffad024-3d44-4e70-bb2f-492d9e4e1e97)

With the laptop's built-in monitor, the vertical alignment of the same folder is incorrect:

![Screenshot from 2024-06-16 21-56-30](https://github.com/G-dH/vertical-workspaces/assets/147217565/d3105d2e-da65-4e5c-ac9f-544a9bfce14a)

**Comment by G-dH** [comment] 2024-06-16 20:08
Thanks. The centering of folders is OK, it looks better to me when a smaller folder is closer to the top edge rather than in the center.

**Comment by G-dH** [comment] 2024-06-16 20:20
But the DND from the folder should be fixed, I'm unable to reproduce the bug anymore.

**Comment by meybonomme** [comment] 2024-06-16 20:25
> Thanks. The centering of folders is OK, it looks better to me when a smaller folder is closer to the top edge rather than in the center.

I agree about the small folders, but the screenshots have full-height folders for each monitor. If the app grid is vertically centered, full-height folders should be as well for a nicer, more consistent design. The current solution seems a bit out of place to me.

**Comment by meybonomme** [comment] 2024-06-16 20:27
> But the DND from the folder should be fixed, I'm unable to reproduce the bug anymore.

Yes, as I said in my previous post :wink: 

> It seems that you have also successfully fixed the upstream folder bug, because it has no longer occurred when dragging the icons out of the folder. Good job!

**Comment by G-dH** [comment] 2024-06-16 20:28
> Unfortunately, when I drag the icons out of the folder, the app grid bug is still there and I get the following results:

?

**Comment by G-dH** [comment] 2024-06-16 20:31
Btw, the vertical position for all folders is calculated the same way: 2/3 of the free space on top and 1/3 on the bottom.

**Comment by meybonomme** [comment] 2024-06-16 20:33
> > Unfortunately, when I drag the icons out of the folder, the app grid bug is still there and I get the following results:
> 
> ?

I meant this upstream bug, it's gone:

![Screenshot from 2024-06-13 02-10-35](https://github.com/G-dH/vertical-workspaces/assets/147217565/c0b72895-a22e-4c13-a3de-3c3bc59242a0)

**Comment by G-dH** [comment] 2024-06-16 20:39
I know. I'm responding to this:
> Unfortunately, when I drag the icons out of the folder, the app grid bug is still there and I get the following results:

**Comment by meybonomme** [comment] 2024-06-16 20:42
> I know. I'm responding to this:
> 
> > Unfortunately, when I drag the icons out of the folder, the app grid bug is still there and I get the following results:

Yes, for some reason I get one of the results shown in the screenshots every time I drag the icon out of the folder.

**Comment by G-dH** [comment] 2024-06-16 20:58
In the default shell, this issue has one condition: an app icon is selected on a different page than where the open folder is located. This can happen when you select the icon using the keyboard, then switch to a different page, open the folder, and drag-and-drop the icon out of the folder. V-Shell now overrides the selection upon opening the folder and selects the folder icon to prevent this issue.

**Comment by meybonomme** [comment] 2024-06-16 21:09
I only used the mouse/touchpad to navigate the app grid and drag icons out of the folder during testing.

**Comment by G-dH** [comment] 2024-06-16 22:07
OK, I was successful in reproducing the issue when I opened the folder with the keyboard. The problem appears to be that the app grid sometimes doesn't recognize which page is currently active despite the current selection. This becomes problematic when dragging the icon, as adjacent pages should move to partially overlap the current one.

**Comment by G-dH** [comment] 2024-06-16 22:21
When migrating icons as you open the app grid, switching monitors causes the Shell to send various sizes to the app grid allocation method in a short period. V-Shell now responds to all these changes, but the final adjustments take effect when the app grid becomes visible.

**Comment by meybonomme** [comment] 2024-06-17 17:16
I will test your brand new update and if necessary, I will open a new issue for each bug I found.

**Closed** 2024-07-07 10:00 UTC
Labels: bug, fixed
