### ISSUE TITLE
[TASK] port to ESM for gnome-shell 45

### ISSUE THREAD

**Issue by mordae** [G-dH/vertical-workspaces#102] opened 2023-08-11 11:31 UTC
Trying to enable the extension by manually editing the supported version field results in the following error being displayed in the extension tool:

> import declarations may only appear at top level of a module

Journal output does not show any further errors.

It seems that a different way to import modules is required. See [gnome-shell-extensions](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/main/extensions) to see what they are doing differently.

**Comment by G-dH** [comment] 2023-08-11 11:48
That's not a bug, that's a fact ;) All extensions must be ported to ESM to work in 45.

**Comment by G-dH** [comment] 2023-08-12 13:03
https://github.com/G-dH/vertical-workspaces/tree/esm-modules
Now you can search for bugs on 45.beta.1 ;)
The workspace thumbnails require some changes to the GS source code that have not yet been implemented.

**Comment by G-dH** [comment] 2023-09-06 18:57
Installation instructions for GNOME 45, all bug reports appreciated!

    git clone https://github.com/G-dH/vertical-workspaces.git
    cd vertical-workspaces
    git checkout esm-modules
    make install

**Comment by carlwgeorge** [comment] 2023-09-08 01:51
I tested the esm-modules branch on Fedora 39 (not yet released) with GNOME 45.beta.1.  It worked great, so I [updated the Fedora package of this extension to a snapshot of that branch](https://bodhi.fedoraproject.org/updates/FEDORA-2023-75a60a3c55).

**Comment by G-dH** [comment] 2023-09-08 06:56
@carlwgeorge Did you test it on Wayland?  My Rawhide only works on X11 for some reason, the Wayland option is not available, but Arch usually fails to start a Wayland session when V-Shell is enabled.  I haven't found the cause yet, there is nothing in the log, the process ends after the first allocation of the report is finished.

**Comment by carlwgeorge** [comment] 2023-09-09 06:22
Yes, I tested it on Wayland, both in a virtual machine and on real hardware.  I also just confirmed that it still works after updating to GNOME 45.rc.  I am testing on Fedora 39, not Rawhide.  Fedora 39 has already branched from Rawhide, so you may be testing on a slightly different environment than I am.

**Comment by G-dH** [comment] 2023-09-09 07:13
Thanks, but the problem exists and I finally found the cause. I'll fix it soon.

**Comment by G-dH** [comment] 2023-09-09 12:05
Now it should be better.

**Comment by mordae** [comment] 2023-09-12 05:54
Love you guys, it works. :-)

**Comment by pcercuei** [comment] 2023-09-19 21:27
Just tested it against Gnome-Shell 45-rc under Debian testing (package version 45.0-1), it is completely unusable. The UI does not respond at all; only right after the session start, when the shell is in overview mode, can I launch an application by searching its name then pressing enter. Trying to open the overview after that is impossible; either via the hot corner or the super key. The rest of the UI cannot be interacted with either, so I cannot close the session or shutdown the computer.

Booting with this extension disabled restores the normal behaviour (just with a horizontal layout).

**Comment by G-dH** [comment] 2023-09-19 21:36
@pcercuei Any other extensions enabled?

**Comment by pcercuei** [comment] 2023-09-19 22:48
@G-dH I tried again with nothing else enabled, same behaviour.

**Comment by thankjura** [comment] 2023-09-19 22:55
gentoo, gnome-45. All UI freeze after startup animation.

<pre>JS ERROR: Exception in callback for signal: trigger: TypeError: Ui.Main.overview.resetOverviewMode is not a function
                                                  _toggleOverview@file:///home/jura/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/layout.js:329:34
                                                  _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                                  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                                  _trigger@resource:///org/gnome/shell/ui/layout.js:1401:14
                                                  _onBarrierHit@resource:///org/gnome/shell/ui/layout.js:1443:18
                                                  @resource:///org/gnome/shell/ui/init.js:21:20
JS ERROR: Exception in callback for signal: trigger: TypeError: Ui.Main.overview.resetOverviewMode is not a function
                                                  _toggleOverview@file:///home/jura/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/layout.js:329:34
                                                  _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                                  _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                                  _trigger@resource:///org/gnome/shell/ui/layout.js:1401:14
                                                  _onBarrierHit@resource:///org/gnome/shell/ui/layout.js:1443:18
                                                  @resource:///org/gnome/shell/ui/init.js:21:20
JS ERROR: TypeError: Ui.overview is undefined
                                                  _updateThumbnailVisibility@file:///home/jura/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspacesView.js:445:13
                                                  _workspacesOnPrimaryChanged@resource:///org/gnome/shell/ui/workspacesView.js:729:14
                                                  _init@resource:///org/gnome/shell/ui/workspacesView.js:619:14
                                                  SecondaryMonitorDisplay@resource:///org/gnome/shell/ui/workspacesView.js:585:1
                                                  _updateWorkspacesViews@file:///home/jura/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspacesView.js:783:24
                                                  prepareToEnterOverview@resource:///org/gnome/shell/ui/workspacesView.js:991:14
                                                  prepareToEnterOverview@resource:///org/gnome/shell/ui/overviewControls.js:713:33
                                                  prepareToEnterOverview@resource:///org/gnome/shell/ui/overview.js:87:24
                                                  _animateVisible@resource:///org/gnome/shell/ui/overview.js:576:24
                                                  show@resource:///org/gnome/shell/ui/overview.js:557:14
                                                  toggle@resource:///org/gnome/shell/ui/overview.js:668:18
                                                  vfunc_event@resource:///org/gnome/shell/ui/panel.js:460:31
                                                  @resource:///org/gnome/shell/ui/init.js:21:20
</pre>

**Comment by carlwgeorge** [comment] 2023-09-19 23:38
This worked for me previously on GNOME 45.rc, but now it doesn't.  I can enable the extension, but then the following doesn't work:

- overview via super key
- moving applications with the mouse
- closing applications by clicking the top right x button
- keyboard input to applications

The UI isn't completely frozen; the follow does work:

- switching workspaces with super+pgup/pgdn
- clicking the clock for the notification and calendar drop down menu
- clicking the top right thing for network, VPN, power mode, night light, dark style, etc.

No other extensions are enabled, and I'm still using GNOME 45.rc.  I'm not sure what changed.  Here is the error from my journal.

```
Sep 19 18:24:02 teal gnome-shell[2361]: V-Shell (Vertical Workspaces): enabled
Sep 19 18:24:04 teal gnome-shell[2361]: g_key_file_get_string: assertion 'key_file != NULL' failed
Sep 19 18:24:04 teal gnome-shell[2361]: g_key_file_get_string: assertion 'key_file != NULL' failed
Sep 19 18:24:05 teal gnome-shell[2361]: JS ERROR: TypeError: Ui.overview is undefined
                                        _updateThumbnailVisibility@file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspacesView.js:445:13
                                        _workspacesOnPrimaryChanged@resource:///org/gnome/shell/ui/workspacesView.js:729:14
                                        _init@resource:///org/gnome/shell/ui/workspacesView.js:619:14
                                        SecondaryMonitorDisplay@resource:///org/gnome/shell/ui/workspacesView.js:585:1
                                        _updateWorkspacesViews@file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/workspacesView.js:783:24
                                        prepareToEnterOverview@resource:///org/gnome/shell/ui/workspacesView.js:991:14
                                        prepareToEnterOverview@resource:///org/gnome/shell/ui/overviewControls.js:713:33
                                        prepareToEnterOverview@resource:///org/gnome/shell/ui/overview.js:87:24
                                        _animateVisible@resource:///org/gnome/shell/ui/overview.js:576:24
                                        show@resource:///org/gnome/shell/ui/overview.js:557:14
                                        toggle@resource:///org/gnome/shell/ui/overview.js:668:18
                                        _onOverlayKeyPressed@file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/overlayKey.js:161:30
                                        @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by G-dH** [comment] 2023-09-20 03:45
Interesting, I can't reproduce your issues on any of my test systems with 45.0 X11/Wayland - Fedora, Arch, Ubuntu.
Are you all sure, you're testing the latest version from the `esm-modules` branch with no other extensions enabled?

**Comment by carlwgeorge** [comment] 2023-09-20 04:35
Yes, all other extensions were disabled for me.  When I commented that it worked before I was using commit f97df40, which was the latest commit from the esm-modules branch at the time.  After fully updating the rest of the system (Fedora 39), I started noticing the problems mentioned in this issue.  I rebased my package off commit f2079e4, but that did not resolve the issue.

**Comment by pcercuei** [comment] 2023-09-20 08:36
> Are you all sure you're testing the latest version from the `esm-modules` branch with no other extensions enabled?

Yep I'm sure.

**Comment by G-dH** [comment] 2023-09-20 08:43
Ok, I fixed the crashing (stupid typo).
But it seems like the secondary monitors workspace thumbnails are gone, and it's upstream bug.

**Comment by pcercuei** [comment] 2023-09-20 09:00
That works now, thanks!

**Comment by G-dH** [comment] 2023-09-20 09:02
@pcercuei Can you see the workspace thumbnails on the secondary monitor?

**Comment by G-dH** [comment] 2023-09-20 09:36
Thanks, corner fixed.

**Comment by pcercuei** [comment] 2023-09-20 10:03
Thanks!

Another issue I noticed, is that the app folders are visible in the overview right after starting the session. Exiting the overview then entering it again fixes it.

![Capture d’écran du 2023-09-20 12-00-56](https://github.com/G-dH/vertical-workspaces/assets/403272/fb2903cf-b20e-4350-91d0-83a9c3bf6d4e)

**Comment by G-dH** [comment] 2023-09-20 10:17
@pcercuei Can you see anything in the log?

**Comment by pcercuei** [comment] 2023-09-20 10:24
@G-dH I don't know how to show the log :D

**Comment by G-dH** [comment] 2023-09-20 10:32
`journalctl /usr/bin/gnome-shell -e` for last 1000 lines of the log
`journalctl /usr/bin/gnome-shell -b` for the entire current boot
`journalctl /usr/bin/gnome-shell -b -1` for the previous boot
`journalctl /usr/bin/gnome-shell -f` to follow the log

**Comment by pcercuei** [comment] 2023-09-20 13:29
I get this which appears when starting a session:
```
sept. 20 15:27:35 frank gnome-shell[1744]: Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception
sept. 20 15:27:35 frank gnome-shell[2514]: JS ERROR: TypeError: this._pages[pageIndex] is undefined
                                           _addItemToPage@file:///home/paul/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/iconGrid.js:337:9
                                           moveItem@file:///home/paul/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/iconGrid.js:294:14
                                           moveItem@resource:///org/gnome/shell/ui/iconGrid.js:1325:29
                                           _moveItem@resource:///org/gnome/shell/ui/appDisplay.js:1235:20
                                           _redisplay/<@file:///home/paul/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:797:22
                                           _redisplay@file:///home/paul/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:792:17
                                           _redisplay/<@file:///home/paul/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:773:27
                                           _redisplay@file:///home/paul/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:772:31
                                           _realizeAppDisplayAndFinishSequence/_timeouts.startup1<@file:///home/paul/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/overviewControls.js:613:28
                                           @resource:///org/gnome/shell/ui/init.js:21:20
sept. 20 15:27:35 frank gnome-shell[2514]: g_key_file_get_string: assertion 'key_file != NULL' failed
sept. 20 15:27:35 frank gnome-shell[2514]: g_key_file_get_string: assertion 'key_file != NULL' failed

```

**Comment by G-dH** [comment] 2023-09-20 14:28
@pcercuei Thanks, I'll look into it. You can try disable `Smooth App Grid Animations` option on the `Misc` tab, to avoid this issue during startup.

**Comment by carlwgeorge** [comment] 2023-09-20 23:03
I rebased my package off of commit 8842b6c, and things are working much better now.  The only remaining problem I noticed is that in the overview the power off, suspend, restart, and log out actions do not work.  The same actions in the top right drop down menu work fine.

**Comment by G-dH** [comment] 2023-09-21 00:59
> The only remaining problem I noticed is that in the overview the power off, suspend, restart, and log out actions do not work.

@carlwgeorge What actions do you mean? The once from the search results?

**Comment by carlwgeorge** [comment] 2023-09-21 05:18
Yes, when you hit the super key, start typing "power" or "suspend" or similar, and then hit enter or click the icon that shows up in the search results.  With no extensions enabled it works.  With just this extension enabled, nothing happens.

**Comment by G-dH** [comment] 2023-09-21 06:16
Fixed.
I really appreciate all your bug reports!

**Comment by carlwgeorge** [comment] 2023-09-21 22:41
I can confirm that commit b407aa9 works to resolve the system actions issue.  I'll keep running it and see if I notice anything else amiss.

**Comment by pcercuei** [comment] 2023-09-24 21:25
@G-dH it was almost perfect last time I tried (right after the hot corner fix), today I pulled the latest version and when entering overview, anything on my secondary monitor will disappear - it will only show a very blurred background image. See the attached video.

[Capture vidéo du 2023-09-24 23-22-25.webm](https://github.com/G-dH/vertical-workspaces/assets/403272/399130d5-eea2-4ee5-a7f7-70a24f9d3f55)

**Comment by G-dH** [comment] 2023-09-24 21:39
@pcercuei Log?

**Comment by pcercuei** [comment] 2023-09-24 21:46
Yes, sorry. The attached log is me just opening the overview (at 23th second) then closing the overview (at 25th second).

[log.txt](https://github.com/G-dH/vertical-workspaces/files/12709731/log.txt)

**Comment by G-dH** [comment] 2023-09-25 10:51
@pcercuei Please add `export SHELL_DEBUG=backtrace-warnings` to your `.bash_profile`, restart session, reproduce the issue and show me the log with backtrace (preferably in \`\`\` ...  \`\`\` block instead of _.txt_ file).

**Comment by pcercuei** [comment] 2023-09-25 11:06
Not much change:
```
sept. 25 13:05:01 frank gnome-shell[2524]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
sept. 25 13:05:01 frank gnome-shell[2524]: Can't update stage views actor <unnamed>[<Gjs_ui_workspacesView_ExtraWorkspaceView>:0x55df7220da20] is on because it needs an allocation.
sept. 25 13:05:01 frank gnome-shell[2524]: Can't update stage views actor <unnamed>[<Gjs_ui_workspace_Workspace>:0x55df71e52020] is on because it needs an allocation.
sept. 25 13:05:01 frank gnome-shell[2524]: Can't update stage views actor <unnamed>[<Gjs_ui_workspace_WorkspaceBackground>:0x55df6f432dd0] is on because it needs an allocation.
sept. 25 13:05:01 frank gnome-shell[2524]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55df72294e40] is on because it needs an allocation.
sept. 25 13:05:01 frank gnome-shell[2524]: Can't update stage views actor <unnamed>[<MetaBackgroundGroup>:0x55df6cb389f0] is on because it needs an allocation.
sept. 25 13:05:01 frank gnome-shell[2524]: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x55df6d4a97e0] is on because it needs an allocation.
sept. 25 13:05:01 frank gnome-shell[2524]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55df719934b0] is on because it needs an allocation.
...
sept. 25 13:05:01 frank gnome-shell[2524]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
...
sept. 25 13:05:04 frank gnome-shell[2524]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
```

(The last two lines are repeated a few dozen times)

**Comment by pcercuei** [comment] 2023-09-25 12:38
My bad, I added it to `~/.bashrc` instead of `~/.bash_profile`.

Thanks for the fix!

**Comment by G-dH** [comment] 2023-09-25 13:04
Depends on the distribution, Debian based distributions use `.profile` for system shell (dash).

**Comment by pcercuei** [comment] 2023-09-27 08:44
Small bug (or is it a feature?), the hot corner seems to be present on all connected monitors now.

(Should I keep posting bugs related to Gnome 45 here or create new bug reports?)

**Comment by sandrobonazzola** [comment] 2023-09-27 08:56
Logging in after the boot, I see in the journal several times:

```apache
set 27 10:13:15 gnome-shell[3497]: V-Shell (Vertical Workspaces): enabled
set 27 10:13:15 gnome-shell[3497]: ../clutter/clutter/clutter-actor.c:8775: Actor '<unnamed>[<Gjs_ui_workspaceThumbnail_ThumbnailsBox>:0x5636c26e4ef0]' tried to allocate a size of 1920,00 x -6,00
set 27 10:13:15 gnome-shell[3497]: == Stack trace for context 0x5636c0c3ffa0 ==
set 27 10:13:15 gnome-shell[3497]: #0   5636c0d0b0d8 i   resource:///org/gnome/shell/ui/overviewControls.js:201 (38abeb97b150 @ 1271)
set 27 10:13:15 gnome-shell[3497]: #1   5636c0d0b030 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/overviewControls.js:123 (3d83a58c42e0 @ 204)
set 27 10:13:15 gnome-shell[3497]: #2   5636c0d0af98 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/overviewControls.js:98 (3d83a58c41f0 @ 88)
set 27 10:13:15 gnome-shell[3497]: #3   5636c0d0af08 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/overviewControls.js:67 (3d83a58c4150 @ 142)
set 27 10:13:15 gnome-shell[3497]: #4   5636c0d0ae70 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/extension.js:441 (3d83a58a5150 @ 161)
set 27 10:13:15 gnome-shell[3497]: #5   5636c0d0add0 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/extension.js:294 (3d83a5890c90 @ 119)
set 27 10:13:15 gnome-shell[3497]: #6   5636c0d0ad38 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/extension.js:195 (3d83a5890b00 @ 17)
set 27 10:13:15 gnome-shell[3497]: #7   5636c0d0ac68 i   resource:///org/gnome/shell/ui/extensionSystem.js:194 (38abeb91ba10 @ 396)
set 27 10:13:15 gnome-shell[3497]: #8   5636c0d0abb0 i   resource:///org/gnome/shell/ui/extensionSystem.js:619 (38abeb923290 @ 381)
set 27 10:13:15 gnome-shell[3497]: #9   5636c0d0ab18 i   self-hosted:1461 (2bbbe059c6f0 @ 30)
set 27 10:13:15 gnome-shell[3497]: #10   7ffffe02d2e0 b   self-hosted:852 (2bbbe059c470 @ 15)
set 27 10:13:15 gnome-shell[3497]: #11   5636c0d0aa88 i   resource:///org/gnome/shell/ui/init.js:21 (10debc670ba0 @ 48)
set 27 10:13:15 gnome-shell[3497]: ../clutter/clutter/clutter-actor.c:8775: Actor '<unnamed>[<Gjs_ui_workspaceThumbnail_ThumbnailsBox>:0x5636c26e4ef0]' tried to allocate a size of 1920,00 x -6,00
set 27 10:13:15 gnome-shell[3497]: == Stack trace for context 0x5636c0c3ffa0 ==
set 27 10:13:15 gnome-shell[3497]: #0   7ffffe02ac00 b   resource:///org/gnome/shell/ui/overviewControls.js:201 (38abeb97b150 @ 1271)
set 27 10:13:15 gnome-shell[3497]: #1   5636c0d0b050 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:231 (3d83a58adba0 @ 1006)
set 27 10:13:15 gnome-shell[3497]: #2   5636c0d0afa8 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:155 (3d83a58adab0 @ 145)
set 27 10:13:15 gnome-shell[3497]: #3   5636c0d0af08 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:84 (3d83a58ad970 @ 166)
set 27 10:13:15 gnome-shell[3497]: #4   5636c0d0ae70 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/extension.js:499 (3d83a58a5150 @ 851)
set 27 10:13:15 gnome-shell[3497]: #5   5636c0d0add0 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/extension.js:294 (3d83a5890c90 @ 119)
set 27 10:13:15 gnome-shell[3497]: #6   5636c0d0ad38 i   file:///usr/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/extension.js:195 (3d83a5890b00 @ 17)
set 27 10:13:15 gnome-shell[3497]: #7   5636c0d0ac68 i   resource:///org/gnome/shell/ui/extensionSystem.js:194 (38abeb91ba10 @ 396)
set 27 10:13:15 gnome-shell[3497]: #8   5636c0d0abb0 i   resource:///org/gnome/shell/ui/extensionSystem.js:619 (38abeb923290 @ 381)
set 27 10:13:15 gnome-shell[3497]: #9   5636c0d0ab18 i   self-hosted:1461 (2bbbe059c6f0 @ 30)
set 27 10:13:15 gnome-shell[3497]: #10   7ffffe02d2e0 b   self-hosted:852 (2bbbe059c470 @ 15)
set 27 10:13:15 gnome-shell[3497]: #11   5636c0d0aa88 i   resource:///org/gnome/shell/ui/init.js:21 (10debc670ba0 @ 48)
set 27 10:13:15 gnome-shell[3497]: V-Shell (Vertical Workspaces): disabled
```

**Comment by G-dH** [comment] 2023-09-27 09:23
@sandrobonazzola Please, [install the latest version from the repository](https://github.com/G-dH/vertical-workspaces/issues/102#issuecomment-1708925452). The second part of the log is not important.

**Comment by carlwgeorge** [comment] 2023-09-27 16:02
gnome-shell-extension-vertical-workspaces-37.5^2.b9220e9-1.fc39.noarch that @sandrobonazzola is using is the Fedora package built from commit b9220e9, which is currently the latest in the esm-modules branch.

**Comment by G-dH** [comment] 2023-09-27 16:52
@sandrobonazzola Any other extensions enabled? The error line shouldn't by accessible when V-Shell is enabled, it should be overridden by the custom allocation method.

**Comment by sandrobonazzola** [comment] 2023-09-28 13:23
```console
$ gnome-extensions list
apps-menu@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org
places-menu@gnome-shell-extensions.gcampax.github.com
user-theme@gnome-shell-extensions.gcampax.github.com
vertical-workspaces@G-dH.github.com

$ rpm -qa |grep gnome-shell-ext
gnome-shell-extension-background-logo-45~beta-1.fc39.noarch
gnome-shell-extension-common-45.0-1.fc39.noarch
gnome-shell-extension-apps-menu-45.0-1.fc39.noarch
gnome-shell-extension-places-menu-45.0-1.fc39.noarch
gnome-shell-extension-user-theme-45.0-1.fc39.noarch
gnome-shell-extension-vertical-workspaces-37.5^2.b9220e9-1.fc39.noarch
```

**Comment by G-dH** [comment] 2023-09-28 13:34
@sandrobonazzola Is it just about the log or are you experiencing any issues?

**Comment by sandrobonazzola** [comment] 2023-09-28 13:53
I don't see any visible effect, just about the log: I assume the warning is there for a reason :-)

**Comment by G-dH** [comment] 2023-09-28 14:18
Extensions override the Shell code at runtime, so this may be the result of less than ideal timing when enabling extensions. In this case the overview's original `allocate()` method called instead of the V-Shell's custom one, but since it's called many times during the startup animation and subsequent calls were apparently handled by V-Shell, the impact is not visible.

**Comment by FoxxMD** [comment] 2023-10-12 14:38
Just reported that `esm-modules` branch works perfectly for me:

* Gnome 45.0
* EndeavourOS (6.5.7-arch1-1)

thanks for the hard work @G-dH !

**Comment by G-dH** [comment] 2023-11-20 20:35
I just switched branches:
`main` moved to `gnome-42-44`
`esm-modules` moved to `main`

[Installation instructions updated](https://github.com/G-dH/vertical-workspaces#installation-from-github-repository).

**Closed** 2023-11-25 20:11 UTC
