### ISSUE TITLE
[BUG] Scrolling to the wrong page after dragging an icon from a folder to a specific page

### ISSUE THREAD

**Issue by meybonomme** [G-dH/vertical-workspaces#173] opened 2024-06-17 18:58 UTC
If I simply drag the icon out of the folder, it is set as the last icon and the app grid scrolls to that page to show the newly dragged icon. When I drag the icon to a specific page, it drops to the right place, but the app grid scrolls itself to the first page.

https://github.com/G-dH/vertical-workspaces/assets/147217565/36c3d346-5d27-4e6e-905f-04032467bb35

**Comment by G-dH** [comment] 2024-06-17 19:04
Can you reproduce this issue using the mouse?

**Comment by meybonomme** [comment] 2024-06-17 19:09
I used a mouse when I did this screencast.

**Comment by G-dH** [comment] 2024-06-17 19:23
So the issue is that the grid switches back to the page with the folder.

**Comment by G-dH** [comment] 2024-06-19 18:08
Fixed, except for the last item in the folder.

**Comment by meybonomme** [comment] 2024-06-19 19:05
https://github.com/G-dH/vertical-workspaces/assets/147217565/4c12e5b7-d4f6-425f-ab60-eaa40d11b4b7



> Fixed, except for the last item in the folder.

My quick test showed that it works with last item in the folder too.

**Comment by G-dH** [comment] 2024-06-19 19:21
When there is only one item in the folder and you drag it out to a specific place in the main grid, it will be placed as the last item in the grid instead of the chosen place. However, It will be focused correctly.

**Comment by G-dH** [comment] 2024-06-19 19:30
So this bug can be labeled as fixed.

**Comment by meybonomme** [comment] 2024-06-19 19:33
> So this bug can be labeled as fixed.

Did you watch my last posted screencast with overlapping icons?

**Comment by G-dH** [comment] 2024-06-19 19:40
:

**Comment by meybonomme** [comment] 2024-06-19 19:45
https://github.com/G-dH/vertical-workspaces/assets/147217565/eb9092aa-dae2-4f7f-8684-6ee0f04d502f

**Comment by G-dH** [comment] 2024-06-19 19:48
But that's a different bug, right?

**Comment by meybonomme** [comment] 2024-06-20 03:09
This happened after yesterday's update.

**Comment by G-dH** [comment] 2024-06-20 07:13
The yesterday's commit doesn't include changes that could cause this. In any case, it's a different issue.

**Comment by meybonomme** [comment] 2024-06-20 17:02
Is this another upstream bug? Am I starting a new issue?

**Comment by meybonomme** [comment] 2024-06-20 17:04
> So this bug can be labeled as fixed.

Yes, the bug for this issue has been fixed.

**Comment by G-dH** [comment] 2024-06-25 21:47
> When there is only one item in the folder and you drag it out to a specific place in the main grid, it will be placed as the last item in the grid instead of the chosen place. However, It will be focused correctly.

This bug is now fixed.

**Comment by meybonomme** [comment] 2024-06-26 00:26
I installed the updates and all the DnD related issues seem to be gone now.

Are just the page dots now too close to the dock again, or has the entire app grid shifted down? I don't understand exactly. Screenshots with laptop monitor and external monitor:

![Screenshot from 2024-06-26 02-51-00](https://github.com/G-dH/vertical-workspaces/assets/147217565/ae2eab51-1881-4e14-a09e-a7cf0b41f14d)

![Screenshot from 2024-06-26 02-54-45](https://github.com/G-dH/vertical-workspaces/assets/147217565/9b69c905-aa8c-4fbd-b22f-bc3d3522ae6e)

**Comment by meybonomme** [comment] 2024-06-27 00:32
I didn't open a new issue because this bug appeared after the last DnD fixes.
When opening the folder, it is easy to see that not only the dots, but the entire application grid has shifted too far down:

![Screenshot from 2024-06-27 03-28-34](https://github.com/G-dH/vertical-workspaces/assets/147217565/fc2d38cb-2910-4ea0-91e9-f1513bbf74a3)

**Comment by G-dH** [comment] 2024-06-27 05:52
It's the missing margin of DtD, which the default dash has. Will be fixed in the next update.

**Comment by G-dH** [comment] 2024-06-28 20:45
I've refactored all overview allocations, please let me know how it works for you.

**Comment by meybonomme** [comment] 2024-06-29 19:15
Using adaptive rows per page, with internal monitor main app grid looks very fine. 1920x1080 and 100% scaling:

![Screenshot from 2024-06-29 21-12-23](https://github.com/G-dH/vertical-workspaces/assets/147217565/28ab4ac0-abf9-4a5a-9301-69f25e7fe1e5)


External monitor with 2560x1440 and 125% scaling have now only 4 rows instead of 5. It looks too empty and impractical room wasting:

![Screenshot from 2024-06-29 21-54-20](https://github.com/G-dH/vertical-workspaces/assets/147217565/70960e39-f1cd-4a62-9563-8e9a1bd4a0ec)


Folder content looks bit out of a place. Page dots are too close to folder bottom edge and the app grid also seems too close to the bottom edge:

![Screenshot from 2024-06-29 21-15-05](https://github.com/G-dH/vertical-workspaces/assets/147217565/07756f65-8c71-443c-92e0-dacdae5bd303)

**Comment by meybonomme** [comment] 2024-06-29 19:23
If I set folder rows per page from adaptive to 5 or more, folder have still only 4 rows.

**Comment by G-dH** [comment] 2024-06-30 05:03
Please, open a new issue for every new bug.

**Comment by G-dH** [comment] 2024-06-30 05:40
> External monitor with 2560x1440 and 125% scaling have now only 4 rows instead of 5. It looks too empty and impractical room wasting

Have you set page height to max?

**Comment by meybonomme** [comment] 2024-07-02 17:29
> Have you set the page height to max?

My mistake, I missed this setting. Since you changed the algorithm for calculating the scale factor, I only had to change the App Grid Page Height Scale from 90 to 95.

> I've refactored all overview allocations, please let me know how it works for you.

Overly it works fine.

> Please, open a new issue for every new bug.

I understand, otherwise it will be difficult for you to track known bugs. I will open new issues.

**Comment by meybonomme** [comment] 2024-07-02 18:13
I feel like this issue can be closed since the original issue is nicely resolved.

**Closed** 2024-07-07 09:57 UTC
Labels: bug, fixed
