### ISSUE TITLE
[BUG] Dash is only visible for a few seconds after enabling extension

### ISSUE THREAD

**Issue by BlueGoliath** [G-dH/vertical-workspaces#73] opened 2023-05-07 04:15 UTC
**Describe the bug**
After enabling the extension on Gnome 44, the dash is only visible and usable for the first few seconds. Sometimes virtual desktops/workspaces can be seen under the dash. All of the opened windows appear to be moved over unnaturally to the right. When attempting to search for something, the search field is under the date and time instead of under it.

**Basic debug information**
 - Did disabling all other extensions help? No.
 - Did you find conflicting extension? No.

**To Reproduce**

Enable the extension then click "activities".

**Expected behavior**
Dash visible and usable. Icons and windows in the center of the screen.

**Screenshots**

**System:**
 - OS: [e.g. Fedora 38] Arch.
 - Version of V-Shell extension: [e.g. 25] 25. 
 - Source of installation: [e.g. extension.gnome.org, GitHub] Github. Can't download from Gnome extensions right now due to Python issues in arch I think.
 - Other installed and enabled extensions: None.
 - 
**System log output**

g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed
V-Shell (Vertical Workspaces): disabled
V-Shell (Vertical Workspaces): enabled
g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed
g_key_file_get_string: assertion 'key_file != NULL' failed

**Comment by G-dH** [comment] 2023-05-07 10:01
Thanks for the report, but I can't reproduce it on my Arch installation and the log is not relevant to your problem. It seems like a conflict with another extension, are you sure you're testing it on a default Shell? You can check that from looking glass (Alt+F2, lg, Enter) and executing this: `Main.extensionManager._enabledExtensions`.
The V-Shell version you're using should be 29.5, not 25.

**Comment by G-dH** [comment] 2023-05-09 21:39
Remove all those extensions (you can just move their folders from `~/.local/share/gnome-shell/extensions` somewhere else just for the test) and restart the session, or test the V-Shell in new user account.

**Comment by G-dH** [comment] 2023-05-23 18:48
Any news? ;)

**Comment by G-dH** [comment] 2023-05-25 04:42
Have you tried resetting all V-Shell options on the About tab of Settings window? Then restart GNOME Shell.

**Comment by G-dH** [comment] 2023-05-25 05:23
There must be something wrong with your user account if it works in another one. Can you add some screenshots of how it looks?

**Comment by G-dH** [comment] 2023-05-25 06:35
I've made some significant changes in the code recently, can you update V-Shell from the repository?

**Comment by G-dH** [comment] 2023-05-25 06:57
Bugged must be your GNOME configuration if it works OK in another account. What about the log, anything relevant?

**Comment by G-dH** [comment] 2023-05-25 07:10
One more thing to try - open d-conf editor and reset all _vertical-workspaces_ schema keys:
![Screenshot from 2023-05-25 09-06-49](https://github.com/G-dH/vertical-workspaces/assets/73719686/041b95e5-1adc-42bd-86b4-00fdbdb2c318)
Don't forget to apply changes.

**Comment by G-dH** [comment] 2023-05-25 07:22
OK, still seems like a conflict with another extension / modification of GS. Have a good night.

**Comment by Cyclic3** [comment] 2023-06-07 01:17
I've had this bug too (trying out the latest arch version), and after creating a new user account, I have found what I believe to be the cause (at least for me):

If you enable the "reduce animation" accessibility feature on a fresh gnome3 profile with v-shell, the search bar moves too far up and the dash disappears, just like as described before.

Turning it off makes it work again, but that option costs me _precious_ milliseconds in opening programs, which is therefore unacceptable.

*Sometimes*, when closing the activities screen, the following output gets dumped into `journalctl -xe` as well, with "reduced animation" both on and off:
[a.txt](https://github.com/G-dH/vertical-workspaces/files/11671515/a.txt)

Interestingly, with "reduced animation" off (i.e. when everything appears to be working), I get the following spammed into *every* time I open the activities screen:

```
Jun 07 02:09:30 archlinux gnome-shell[10687]: Can't update stage views actor <unnamed>[<StBin>:0x55758d13e060] is on because it needs an allocation.
```

If there's any more information I can provide, please let me know

**Comment by G-dH** [comment] 2023-06-07 06:17
@Cyclic3 : Thanks, I'll look into it. However, you can set the *Animation Speed* slider in the V-Shell's Settings window (*Behavior* tab) to *1* to reduce the animation time without the issue. Also enabling the *Show Workspace Preview Background* option in the *Appearance* tab should help, because the missing background is why the overview contents need to be animated.

**Comment by G-dH** [comment] 2023-06-07 07:38
> My only gripe is that Gnome 3 profile has search / recent history buttons in the dock 

Disable the icons in Settings *Layout* tab and save the updated profile.

> the workspaces preview is shown even if there is only one workspace

V-Shell is about workspaces, but if you don't use them, you can disable the ws thumbnails. You can also reduce its size.
And again, you can save all your changes, including profile name, to any of the 4 profiles.

**Comment by Cyclic3** [comment] 2023-06-07 11:19
Each of the suggested workaround and commit 8884857 fix it on my machine. Thanks for sorting this out so quickly!

**Comment by G-dH** [comment] 2023-06-07 11:29
Thanks for feedback :)

**Closed** 2023-06-09 12:37 UTC
Labels: bug
